---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
  namespace: maven-ns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebappcontainer
          image: dockerlanthony/maven-web-application:6d818336616b471f757243a1fe1fb6f48641627b
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: maven-ns
spec:
  selector:
    app: mavenwebapp
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: maven-ingress-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-application
spec:
  hosts:
    - "*"
  gateways:
    - maven-ingress-gateway
  http:
    - route:
        - destination:
            host: mavenwebappsvc.maven-ns.svc.cluster.local
            port:
              name: http
              number: 80
